version = 1

[common]
# API 模式：设为 true 时将禁止加载本地订阅或直接提供本地文件
api_mode = false
# 用于通过 Web 界面执行关键操作的访问令牌
api_access_token = "password"
# 默认 URL，当请求中未提供 URL 时使用。多个订阅链接之间用 "|" 分隔，支持本地文件/URL
default_url = []
# 插入订阅链接，适用于在所有导出的订阅中添加节点
enable_insert = true
# 插入的 URL 列表，可用于在所有导出的订阅中添加节点，支持本地文件/URL
insert_url = [""]
# 将插入的 URL 预置到订阅链接之前，insert_url 中的节点会优先加入不含组匹配模式的分组
prepend_insert_url = true
# 排除备注符合下列正则表达式的节点
exclude_remarks = ["(到期|剩余流量|时间|官网|产品)"]
# 是否启用脚本支持以过滤节点
enable_filter = false
# 外部配置文件作用域限制
base_path = "base"
# 各平台配置模板路径
clash_rule_base = "base/all_base.tpl"
surge_rule_base = "base/all_base.tpl"
surfboard_rule_base = "base/all_base.tpl"
mellow_rule_base = "base/all_base.tpl"
quan_rule_base = "base/all_base.tpl"
quanx_rule_base = "base/all_base.tpl"
loon_rule_base = "base/all_base.tpl"
sssub_rule_base = "base/all_base.tpl"
singbox_rule_base = "base/all_base.tpl"
# 下载规则集或订阅时所使用的代理配置，支持 cURL 格式的代理（http://、https://、socks4a://、socks5://）
proxy_config = "SYSTEM"
proxy_ruleset = "SYSTEM"
proxy_subscription = "NONE"
# 是否在节点备注中附加代理类型字符串（如 [SS]、[SSR]、[VMess]）
append_proxy_type = false
# 请求 /sub 时是否先重新加载本配置文件
reload_conf_on_request = false

[[userinfo.stream_rule]]
match = '^剩余流量：(.*?)\|总流量：(.*)$'
replace = 'total=$2&left=$1'

[[userinfo.stream_rule]]
match = '^剩余流量：(.*?) (.*)$'
replace = 'total=$1&left=$2'

[[userinfo.stream_rule]]
match = '^Bandwidth: (.*?)/(.*)$'
replace = 'used=$1&total=$2'

[[userinfo.stream_rule]]
match = '^.*剩余(.*?)(?:\s*?)@(?:.*)$'
replace = 'total=$1'

[[userinfo.time_rule]]
match = '^过期时间：(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)$'
replace = '$1:$2:$3:$4:$5:$6'

[[userinfo.time_rule]]
match = '^到期时间:(\d+)-(\d+)-(\d+)$'
replace = '$1:$2:$3:0:0:0'

[[userinfo.time_rule]]
match = '^Smart Access expire: (\d+)/(\d+)/(\d+)$'
replace = '$1:$2:$3:0:0:0'

[node_pref]
sort_flag = false
filter_deprecated_nodes = false
append_sub_userinfo = true
clash_use_new_field_name = true
clash_proxies_style = "flow"
clash_proxy_groups_style = "block"
singbox_add_clash_modes = true

[[node_pref.rename_node]]
match = '\(?((x|X)?(\d+)(\.?\d+)?)((\s?倍率?)|(x|X))\)?'
replace = "$1x"

[managed_config]
write_managed_config = true
managed_config_prefix = "http://127.0.0.1:25500"
config_update_interval = 86400
config_update_strict = false
quanx_device_id = ""

[surge_external_proxy]
resolve_hostname = true

[emojis]
add_emoji = false
remove_old_emoji = true

[[emojis.emoji]]
match = '(流量|时间|应急)'
emoji = '️‍'

###############################################################################
# 以下为 custom_groups 分组，每个分组使用独立的表格
###############################################################################

[[custom_groups]]
name = "环球网络"
type = "url-test"
rule = ["[]♻️ 自动选择", "[]⚡ 均衡负载", "[] Ex香港", "[] ZHS香港", "[] Ex台湾", "[] ZHS台湾", "[] Ex星国", "[] ZHS星国", "[] Ex日本", "[] ZHS日本", "[] Ex美国", "[] ZHS美国", "[]⚡ 全部节点", "[] 全部节点", "[]DIRECT", "[]REJECT"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "♻️ 自动选择"
type = "url-test"
rule = [".*"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "Netflix"
type = "url-test"
rule = ["[]♻️ 自动选择", "[]⚡ 均衡负载", "[] Ex香港", "[] ZHS香港", "[] Ex台湾", "[] ZHS台湾", "[] Ex星国", "[] ZHS星国", "[] Ex日本", "[] ZHS日本", "[] Ex美国", "[] ZHS美国", "[]⚡ 全部节点", "[] 全部节点", "[]DIRECT", "[]REJECT"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "拦截连接"
type = "select"
rule = ["[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "漏网之鱼"
type = "select"
rule = ["[]♻️ 自动选择", "[]⚡ 均衡负载", "[] Ex香港", "[] ZHS香港", "[] Ex台湾", "[] ZHS台湾", "[] Ex星国", "[] ZHS星国", "[] Ex日本", "[] ZHS日本", "[] Ex美国", "[] ZHS美国", "[]⚡ 全部节点", "[] 全部节点", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "Telegram"
type = "select"
rule = ["[]♻️ 自动选择", "[]⚡ 均衡负载", "[] Ex香港", "[] ZHS香港", "[] Ex台湾", "[] ZHS台湾", "[] Ex星国", "[] ZHS星国", "[] Ex日本", "[] ZHS日本", "[] Ex美国", "[] ZHS美国", "[]⚡ 全部节点", "[] 全部节点", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "苹果服务"
type = "select"
rule = ["[]♻️ 自动选择", "[]⚡ 均衡负载", "[] Ex香港", "[] ZHS香港", "[] Ex台湾", "[] ZHS台湾", "[] Ex星国", "[] ZHS星国", "[] Ex日本", "[] ZHS日本", "[] Ex美国", "[] ZHS美国", "[]⚡ 全部节点", "[] 全部节点", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "Ⓜ️ 微软服务"
type = "select"
rule = ["[]♻️ 自动选择", "[]⚡ 均衡负载", "[] Ex香港", "[] ZHS香港", "[] Ex台湾", "[] ZHS台湾", "[] Ex星国", "[] ZHS星国", "[] Ex日本", "[] ZHS日本", "[] Ex美国", "[] ZHS美国", "[]⚡ 全部节点", "[] 全部节点", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "SpeedTest"
type = "select"
rule = ["[]♻️ 自动选择", "[]⚡ 均衡负载", "[] Ex香港", "[] ZHS香港", "[] Ex台湾", "[] ZHS台湾", "[] Ex星国", "[] ZHS星国", "[] Ex日本", "[] ZHS日本", "[] Ex美国", "[] ZHS美国", "[]⚡ 全部节点", "[] 全部节点", "[]DIRECT", "[]REJECT"]
 
[[custom_groups]]
name = "AI"
type = "select"
rule = ["[]♻️ 自动选择", "[]⚡ 均衡负载", "[] Ex香港", "[] ZHS香港", "[] Ex台湾", "[] ZHS台湾", "[] Ex星国", "[] ZHS星国", "[] Ex日本", "[] ZHS日本", "[] Ex美国", "[] ZHS美国", "[]⚡ 全部节点", "[] 全部节点", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "香港串流验证"
type = "select"
rule = ["[]♻️ 自动选择", "[]⚡ 均衡负载", "[] Ex香港", "[] ZHS香港", "[] Ex台湾", "[] ZHS台湾", "[] Ex星国", "[] ZHS星国", "[] Ex日本", "[] ZHS日本", "[] Ex美国", "[] ZHS美国", "[]⚡ 全部节点", "[] 全部节点", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "EdgeWare"
type = "select"
rule = ["[]♻️ 自动选择", "[]⚡ 均衡负载", "[] Ex香港", "[] ZHS香港", "[] Ex台湾", "[] ZHS台湾", "[] Ex星国", "[] ZHS星国", "[] Ex日本", "[] ZHS日本", "[] Ex美国", "[] ZHS美国", "[]⚡ 全部节点", "[] 全部节点", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "香港原生"
type = "url-test"
rule = ["HKT|九龙|铠甲|天机|契约|TVB"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "Ex香港"
type = "url-test"
rule = ["^(?!.*(深圳))(?=.*(?:香港)).*$"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "Ex台湾"
type = "url-test"
rule = ["(?=.*(台湾)(?!.*(动画))).*"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "Ex星国"
type = "url-test"
rule = ["^(?=.*(?:星国)).*$"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "ZHS香港"
type = "url-test"
rule = ["^(?!.*(深圳))(?=.*(?:香港)).*$"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "ZHS台湾"
type = "url-test"
rule = ["(?=.*(台湾)(?!.*(动画))).*"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "ZHS星国"
type = "url-test"
rule = ["^(?=.*(?:星国)).*$"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "ZHS日本"
type = "url-test"
rule = ["^(?=.*(?:日本)).*$"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "ZHS美国"
type = "url-test"
rule = ["^(?=.*(?:美国)).*$"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true
